# Site settings
title: Getting Security Done
email: phil@gettingsecuritydone.com
description: >- 
  Business for security leaders. Security for business leaders.
baseurl: ""
url: "https://gettingsecuritydone.github.io"
github_username: gettingsecuritydone

# Theme settings
remote_theme: sylhare/Type-on-Strap
color_theme: auto
header_text: Getting Security Done
footer_text: Copyright 2024

# Post settings
post_navigation: true
paginate: 10
paginate_path: "articles/page:num"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
